events {
    worker_connections 100;
}

http {
    resolver 127.0.0.11 ipv6=off;

    server {
        listen 80;
        listen 443;
        
        location / {
            proxy_pass http://app:8080;
        }
    }
}